const str = { "id": "9c5195d22893c47de777f36d3bb1f610f9799500", "type": "edit", "undefined": "", "mrt_code": "79480", "mrt_name": "uysavd", "mrt_sec_email": "", "mrt_cntry": "IN", "mrt_city": "MBM", "mrt_tag": "GroceryShopping", "mrt_cntct_person": "", "mrt_address": "", "mrt_url": "", "mrt_phn_no": "36724324332", "mrt_lob": "click", "mrt_remark": "", "mrt_status": "1", "is_external_browser": "1", "mrt_participate": "1", "is_pin_based": "1", "redemption_rate": "", "mrt_days": "44", "mrt_tnc": "<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n\n</body>\n</html>", "spend_text": "", "spend_desc": "", "spend_tnc": "<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n\n</body>\n</html>", "click_text": "", "click_desc": "", "click_tnc": "<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n\n</body>\n</html>", "visit_text": "", "visit_desc": "", "visit_tnc": "<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n\n</body>\n</html>", "spend_online_text": "", "spend_online_desc": "", "spend_online_tnc": "<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n\n</body>\n</html>", "spend_instore_text": "", "spend_instore_desc": "", "spend_instore_tnc": "<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n\n</body>\n</html>", "affiliate_text": "", "affiliate_desc": "", "affiliate_tnc": "<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n\n</body>\n</html>", "redeem_text": "", "redeem_desc": "", "redeem_tnc": "<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n\n</body>\n</html>", "redeem_online_text": "", "redeem_online_desc": "", "redeem_online_tnc": "<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n\n</body>\n</html>", "voucher_text": "", "voucher_desc": "", "voucher_tnc": "<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n\n</body>\n</html>", "brand_lob_rates_fields": "{}" };
const convertedString = JSON.stringify(str);

const str1 = { "id": "9c5195d22893c47de777f36d3bb1f610f9799500", "type": "edit", "undefined": "", "mrt_code": "79480", "mrt_name": "uysavd", "mrt_sec_email": "", "mrt_cntry": "IN", "mrt_city": "MBM", "mrt_tag": "GroceryShopping", "mrt_cntct_person": "", "mrt_address": "", "mrt_url": "", "mrt_phn_no": "36724324332", "mrt_lob": "click", "mrt_remark": "", "mrt_status": "1", "is_external_browser": "1", "mrt_participate": "1", "is_pin_based": "1", "redemption_rate": "", "mrt_days": "44", "mrt_tnc": "<!DOCTYPE html>\r\n<html>\r\n<head>\r\n</head>\r\n<body>\r\n\r\n</body>\r\n</html>", "spend_text": "", "spend_desc": "", "spend_tnc": "<!DOCTYPE html>\r\n<html>\r\n<head>\r\n</head>\r\n<body>\r\n\r\n</body>\r\n</html>", "click_text": "", "click_desc": "", "click_tnc": "<!DOCTYPE html>\r\n<html>\r\n<head>\r\n</head>\r\n<body>\r\n\r\n</body>\r\n</html>", "visit_text": "", "visit_desc": "", "visit_tnc": "<!DOCTYPE html>\r\n<html>\r\n<head>\r\n</head>\r\n<body>\r\n\r\n</body>\r\n</html>", "spend_online_text": "", "spend_online_desc": "", "spend_online_tnc": "<!DOCTYPE html>\r\n<html>\r\n<head>\r\n</head>\r\n<body>\r\n\r\n</body>\r\n</html>", "spend_instore_text": "", "spend_instore_desc": "", "spend_instore_tnc": "<!DOCTYPE html>\r\n<html>\r\n<head>\r\n</head>\r\n<body>\r\n\r\n</body>\r\n</html>", "affiliate_text": "", "affiliate_desc": "", "affiliate_tnc": "<!DOCTYPE html>\r\n<html>\r\n<head>\r\n</head>\r\n<body>\r\n\r\n</body>\r\n</html>", "redeem_text": "", "redeem_desc": "", "redeem_tnc": "<!DOCTYPE html>\r\n<html>\r\n<head>\r\n</head>\r\n<body>\r\n\r\n</body>\r\n</html>", "redeem_online_text": "", "redeem_online_desc": "", "redeem_online_tnc": "<!DOCTYPE html>\r\n<html>\r\n<head>\r\n</head>\r\n<body>\r\n\r\n</body>\r\n</html>", "voucher_text": "", "voucher_desc": "", "voucher_tnc": "<!DOCTYPE html>\r\n<html>\r\n<head>\r\n</head>\r\n<body>\r\n\r\n</body>\r\n</html>", "brand_lob_rates_fields": "{}" };
const convertedString1 = JSON.stringify(str1).replace(/\\r/g, "");

console.log(convertedString);
console.log('\n\n\n\n', convertedString1);


